(() => {
  'use strict';
  const store=window.notulensiLiteStorage, recorder=window.NotulensiLiteRecorder, transcription=window.NotulensiLiteTranscription;
  if(!store||!recorder||!transcription)throw new Error('NOTULENSI_LITE_ENGINE_UNAVAILABLE');
  const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const state={sessions:[],version:0,backend:false,recording:false,paused:false,recordingId:null,durationMs:0,finalText:'',interimText:'',currentAudio:null,finalizing:false};
  function localLoad(){const p=store.read();state.sessions=Array.isArray(p.sessions)?p.sessions:[];state.version=Number(p.version)||0;}
  function localSave(){store.write({sessions:state.sessions,version:state.version});}
  async function api(path,opt={}){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||`HTTP_${r.status}`),{status:r.status,data:d});return d;}
  async function hydrate(){try{const auth=await api('/api/admin-session.js');if(!auth.authenticated)return;const d=await api('/api/lite-data.js');if(Array.isArray(d.data?.sessions)){state.sessions=d.data.sessions;state.version=d.version;state.backend=true;await recoverAudioLinks();renderHistory();setMessage('Sinkronisasi cloud aktif.');}}catch{state.backend=false;}}
  async function recoverAudioLinks(){await Promise.all(state.sessions.map(async s=>{if(!s.recordingId)return;try{const audio=await recorder.getRecording(s.recordingId);s.audioAvailable=Boolean(audio?.blob);if(audio?.blob)state.currentAudio=audio;}catch{s.audioAvailable=false;}}));localSave();}
  async function persist(){localSave();if(!state.backend)return;try{const d=await api('/api/lite-data.js',{method:'PUT',headers:{'X-Notulensi-Lite-Request':'1'},body:JSON.stringify({baseVersion:state.version,data:{sessions:state.sessions}})});if(d.conflict){state.sessions=d.data.sessions||[];state.version=d.version;localSave();setMessage('Data berubah di sesi lain; versi server dipertahankan.');}else state.version=d.version;}catch(e){setMessage(e.status===401?'Sesi admin berakhir; data tetap tersimpan lokal.':'Sinkronisasi cloud gagal; data tetap tersimpan lokal.');}}
  function setMessage(x){$('message').textContent=x;}
  function setStatus(label,live=false){$('status').textContent=label;$('dot').classList.toggle('live',live);}
  function fmt(ms){return recorder.formatMs(ms);}
  function renderTimer(e){$('timer').textContent=e.display||fmt(e.elapsed||0);state.durationMs=e.elapsed||0;}
  function renderHistory(){const h=$('history');if(!state.sessions.length){h.innerHTML='<div class="empty">Belum ada sesi tersimpan.</div>';return;}h.innerHTML=state.sessions.map(s=>`<article class="history-item"><div class="history-main"><strong>${esc(s.title)}</strong><span>${esc(new Date(s.createdAt).toLocaleString('id-ID'))}</span></div><div class="muted">${fmt(s.durationMs||0)} · ${s.audioAvailable?'audio lokal tersedia':'transkrip saja'}</div><p>${esc(s.text||'').slice(0,360)}</p><div class="history-actions"><button class="ghost" data-load="${s.id}">Buka</button></div></article>`).join('');}
  function setControls(){const r=state.recording;$('start').disabled=r||state.finalizing;$('pause').disabled=!r||state.paused||state.finalizing;$('resume').disabled=!r||!state.paused||state.finalizing;$('stop').disabled=!r||state.finalizing;$('save').disabled=state.finalizing||r||(!state.finalText.trim()&&!$('text').value.trim());}
  function refreshSupport(){const audio=!!window.MediaRecorder&&!!navigator.mediaDevices?.getUserMedia;const speech=transcription.support();$('support').innerHTML=`<span class="support-chip ${audio?'ok':'bad'}">${audio?'● Audio siap':'● Audio tidak tersedia'}</span><span class="support-chip ${speech?'ok':'warn'}">${speech?'● Transkrip siap':'● Transkrip browser terbatas'}</span>`;}
  async function start(){try{await recorder.start();state.recording=true;state.paused=false;state.recordingId=null;state.currentAudio=null;state.finalText=$('text').value.trim();state.interimText='';setStatus('Sedang merekam',true);setMessage('Mikrofon aktif. Anda dapat berbicara secara normal.');setControls();try{transcription.start()}catch(e){setMessage('Audio aktif; transkripsi browser tidak tersedia. Rekaman tetap berjalan.');}}catch(e){setStatus('Siap merekam');setMessage(e.message==='MICROPHONE_API_UNAVAILABLE'?'Browser tidak menyediakan akses mikrofon.':'Akses mikrofon gagal. Periksa izin browser lalu coba lagi.');}}
  function pause(){recorder.pause();state.paused=true;try{transcription.stop()}catch{}setStatus('Rekaman dijeda');setMessage('Rekaman dijeda. Tekan Lanjutkan untuk meneruskan.');setControls();}
  function resume(){recorder.resume();state.paused=false;try{transcription.start()}catch{}setStatus('Sedang merekam',true);setMessage('Rekaman dilanjutkan.');setControls();}
  async function stop(){if(!state.recording||state.finalizing)return;state.finalizing=true;setControls();try{try{transcription.stop()}catch{}const meta=await recorder.stop();state.recording=false;state.paused=false;state.recordingId=meta?.id||state.recordingId;state.durationMs=meta?.durationMs||state.durationMs;state.currentAudio=meta||null;setStatus('Rekaman selesai');setMessage('Rekaman selesai dan audio lokal sudah diamankan. Periksa transkrip lalu simpan.');}catch(e){state.recording=false;state.paused=false;setStatus('Rekaman selesai');setMessage('Rekaman berhenti, tetapi penyimpanan audio lokal gagal. Transkrip tetap dapat disimpan.');}finally{state.finalizing=false;setControls();}}
  async function save(){const text=$('text').value.trim();if(!text){setMessage('Belum ada transkrip untuk disimpan.');return;}if(state.recording||state.finalizing){setMessage('Tunggu sampai rekaman selesai sebelum menyimpan sesi.');return;}const title=$('title').value.trim()||`Sesi ${new Date().toLocaleString('id-ID')}`;let audio=null;if(state.recordingId){try{audio=await recorder.getRecording(state.recordingId);}catch{}}const session={id:`s_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,title,text,durationMs:state.durationMs,createdAt:new Date().toISOString(),recordingId:audio?.id||state.recordingId||null,audioAvailable:Boolean(audio?.blob)};state.sessions.unshift(session);await persist();renderHistory();setMessage(session.audioAvailable?'Sesi dan hubungan audio tersimpan.':'Sesi tersimpan tanpa audio lokal.');}
  function resetEditor(){if(state.recording||state.finalizing){setMessage('Hentikan rekaman terlebih dahulu.');return;}$('title').value='';$('text').value='';state.finalText='';state.interimText='';state.recordingId=null;state.currentAudio=null;state.durationMs=0;renderTimer({elapsed:0,display:'00:00:00'});setMessage('Sesi baru siap.');setControls();}
  function copy(){navigator.clipboard?.writeText($('text').value).then(()=>setMessage('Transkrip disalin.')).catch(()=>setMessage('Clipboard tidak tersedia.'))}
  function download(){const blob=new Blob([$('text').value],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`notulensi-lite-${Date.now()}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  window.addEventListener('notulensi:lite:timer',e=>renderTimer(e.detail));
  window.addEventListener('notulensi:lite:state',e=>{const s=e.detail.status;if(s==='recording'){state.recording=true;state.paused=false;setStatus('Sedang merekam',true)}if(s==='paused'){state.paused=true;setStatus('Rekaman dijeda')}setControls();});
  window.addEventListener('notulensi:lite:stopped',e=>{state.recordingId=e.detail.id;state.durationMs=e.detail.durationMs||state.durationMs;state.currentAudio=e.detail;setControls();});
  window.addEventListener('notulensi:lite:transcription:result',e=>{state.finalText=e.detail.finalText||'';state.interimText=e.detail.interimText||'';$('text').value=e.detail.combined||'';setControls();});
  window.addEventListener('notulensi:lite:transcription:error',e=>{if(!state.recording)return;setMessage(`Transkripsi: ${e.detail.code||'error'}. Rekaman audio tetap berjalan.`);});
  $('start').onclick=start;$('pause').onclick=pause;$('resume').onclick=resume;$('stop').onclick=stop;$('save').onclick=save;$('copy').onclick=copy;$('download').onclick=download;$('clear').onclick=resetEditor;
  $('text').addEventListener('input',()=>{state.finalText=$('text').value;state.interimText='';setControls()});
  $('history').addEventListener('click',async e=>{const id=e.target.closest('[data-load]')?.dataset.load;if(!id)return;const s=state.sessions.find(x=>x.id===id);if(s){$('title').value=s.title;$('text').value=s.text||'';state.finalText=s.text||'';state.durationMs=s.durationMs||0;state.recordingId=s.recordingId||null;state.currentAudio=null;if(state.recordingId){try{state.currentAudio=await recorder.getRecording(state.recordingId);}catch{}}renderTimer({elapsed:state.durationMs,display:fmt(state.durationMs)});setMessage(state.currentAudio?.blob?'Sesi dibuka; audio lokal tersedia.':'Sesi dibuka untuk ditinjau.');setControls();}});
  localLoad();refreshSupport();renderTimer({elapsed:0,display:'00:00:00'});setControls();renderHistory();hydrate();
})();
