(() => {
  'use strict';
  const state = { transcripts: [], recorder: null, stream: null, chunks: [], recordBlob: null, recordStartedAt: 0, timer: null };
  const store = window.notulensiLiteStorage;
  if (!store) throw new Error('NOTULENSI_LITE_STORAGE_UNAVAILABLE');
  const id=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
  const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  function localLoad(){const p=store.read();state.transcripts=Array.isArray(p.transcripts)?p.transcripts:[];}
  function localSave(){store.write({meetings:[],transcripts:state.transcripts});}
  function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));const t=document.getElementById(view);if(t)t.classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));}
  function render(){document.getElementById('recordingCount').textContent=state.recordBlob?1:0;document.getElementById('transcriptCount').textContent=state.transcripts.length;document.getElementById('transcriptList').innerHTML=state.transcripts.length?state.transcripts.map(t=>`<article class="item" data-transcript="${esc(t.id)}"><span class="badge">Transkrip</span><strong> ${esc(t.title||'Tanpa judul')}</strong><div>${esc(t.body||'').slice(0,220)}</div></article>`).join(''):'<div class="empty">Belum ada transkrip.</div>';}
  function fmt(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`;}
  function recordUi(recording){document.getElementById('recordPanel').classList.toggle('recording',recording);document.getElementById('startRecording').disabled=recording;document.getElementById('stopRecording').disabled=!recording;document.getElementById('downloadRecording').disabled=!state.recordBlob;}
  function preview(){const audio=document.getElementById('recordPreview');if(!state.recordBlob){audio.classList.add('hidden');return;}if(audio.src.startsWith('blob:'))URL.revokeObjectURL(audio.src);audio.src=URL.createObjectURL(state.recordBlob);audio.classList.remove('hidden');recordUi(false);}
  async function startRecording(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){document.getElementById('recordStatus').textContent='Browser tidak mendukung perekaman audio.';return;}state.stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];state.recordBlob=null;state.recordStartedAt=Date.now();state.recorder=new MediaRecorder(state.stream);state.recorder.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data);};state.recorder.onstop=async()=>{state.recordBlob=new Blob(state.chunks,{type:state.recorder.mimeType||'audio/webm'});state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;clearInterval(state.timer);document.getElementById('recordTimer').textContent=fmt(Date.now()-state.recordStartedAt);document.getElementById('recordStatus').textContent=`Rekaman siap (${Math.round(state.recordBlob.size/1024)} KB).`;try{await store.putRecording(state.recordBlob);preview();render();}catch(e){document.getElementById('recordStatus').textContent='Rekaman siap, tetapi penyimpanan lokal gagal.';preview();render();}};state.recorder.start();state.timer=setInterval(()=>document.getElementById('recordTimer').textContent=fmt(Date.now()-state.recordStartedAt),250);document.getElementById('recordStatus').textContent='Sedang merekam…';recordUi(true);}
  function stopRecording(){if(state.recorder?.state==='recording')state.recorder.stop();}
  function downloadRecording(){if(!state.recordBlob)return;const a=document.createElement('a');a.href=URL.createObjectURL(state.recordBlob);a.download=`notulensi-lite-${new Date().toISOString().replace(/[:.]/g,'-')}.webm`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
  document.getElementById('startRecording').onclick=()=>startRecording().catch(e=>document.getElementById('recordStatus').textContent=`Gagal memulai rekaman: ${e.message}`);
  document.getElementById('stopRecording').onclick=stopRecording;document.getElementById('downloadRecording').onclick=downloadRecording;
  document.getElementById('newTranscript').onclick=()=>{document.getElementById('tTitle').value='';document.getElementById('tBody').value='';document.getElementById('transcriptEditor').classList.remove('hidden');show('transcripts');};
  document.getElementById('cancelTranscript').onclick=()=>document.getElementById('transcriptEditor').classList.add('hidden');
  document.getElementById('saveTranscript').onclick=()=>{const t={id:id('t'),title:document.getElementById('tTitle').value.trim(),body:document.getElementById('tBody').value.trim(),updatedAt:new Date().toISOString()};if(!t.title||!t.body){alert('Judul dan isi transkrip wajib diisi.');return;}state.transcripts.unshift(t);localSave();document.getElementById('transcriptEditor').classList.add('hidden');render();};
  document.getElementById('transcriptList').addEventListener('click',e=>{const el=e.target.closest('[data-transcript]');if(el){const t=state.transcripts.find(x=>x.id===el.dataset.transcript);if(t)alert(`${t.title}\n\n${t.body}`);}});
  localLoad();render();recordUi(false);store.getRecording().then(r=>{if(r?.blob){state.recordBlob=r.blob;document.getElementById('recordStatus').textContent=`Rekaman tersimpan (${Math.round(r.blob.size/1024)} KB).`;preview();render();}}).catch(()=>{});
})();
