import { Pool } from 'pg';

const DEFAULT={enabled:true,affiliate:{enabled:true,network:'Shopee Affiliate',items:[]}};
let pool;
function db(){const s=process.env.DATABASE_URL||process.env.notulensi_POSTGRES_URL||process.env.notulensi_POSTGRES_PRISMA_URL||process.env.notulensi_DATABASE_URL_UNPOOLED;if(!s)throw new Error('DATABASE_URL is not configured.');if(!pool)pool=new Pool({connectionString:s,max:2,ssl:process.env.DATABASE_SSL==='disable'?false:{rejectUnauthorized:false}});return pool;}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function wrap(text,max){const words=String(text||'').split(/\s+/);const lines=[];let line='';for(const w of words){if((line+' '+w).trim().length>max){if(line)lines.push(line);line=w}else line=(line+' '+w).trim()}if(line)lines.push(line);return lines.slice(0,3);}
async function config(client){await client.query(`CREATE TABLE IF NOT EXISTS notulensi_monetization_config (config_key TEXT PRIMARY KEY, config JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);const r=await client.query('SELECT config FROM notulensi_monetization_config WHERE config_key=$1',['default']);return r.rows[0]?.config||DEFAULT;}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','image/svg+xml; charset=utf-8');if(req.method!=='GET')return res.status(405).end();const client=await db().connect();try{const c=await config(client);const id=String(req.query?.id||'');const item=(c.affiliate?.items||[]).find(x=>String(x.id)===id)|| (c.affiliate?.items||[]).find(x=>x.url);if(!c.enabled||!c.affiliate?.enabled||!item?.url)return res.status(404).end();const title=wrap(item.title||'Rekomendasi untuk rapat',28);const desc=wrap(item.description||'',44);const href=esc(item.url);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="360" viewBox="0 0 900 360"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#312e81"/><stop offset="1" stop-color="#0e7490"/></linearGradient></defs><rect width="900" height="360" rx="28" fill="#020617"/><rect x="14" y="14" width="872" height="332" rx="22" fill="url(#g)"/><circle cx="770" cy="100" r="74" fill="#fff" opacity=".08"/><circle cx="820" cy="160" r="120" fill="#fff" opacity=".05"/><text x="52" y="68" fill="#bae6fd" font-family="Arial,sans-serif" font-size="22" font-weight="700">${esc(c.affiliate.network||'Affiliate')}</text>${title.map((x,i)=>`<text x="52" y="${122+i*38}" fill="#fff" font-family="Arial,sans-serif" font-size="32" font-weight="700">${esc(x)}</text>`).join('')}${desc.map((x,i)=>`<text x="52" y="${225+i*24}" fill="#cbd5e1" font-family="Arial,sans-serif" font-size="18">${esc(x)}</text>`).join('')}<rect x="52" y="290" width="190" height="38" rx="19" fill="#fff"/><text x="147" y="315" text-anchor="middle" fill="#0f172a" font-family="Arial,sans-serif" font-size="16" font-weight="700">${esc(item.label||'Lihat rekomendasi')}</text><text x="820" y="315" text-anchor="end" fill="#cbd5e1" font-family="Arial,sans-serif" font-size="13">Rekomendasi afiliasi</text></svg>`;return res.status(200).send(svg)}catch(e){console.error('affiliate-ad',e);return res.status(503).end()}finally{client.release();}}
