import { Pool } from 'pg';
import { requireAdmin } from './_admin-auth.js';
const DEFAULT_CONFIG={enabled:true,adsense:{enabled:false,publisherId:'',slots:{}},affiliate:{enabled:true,network:'Shopee Affiliate',disclosure:'Rekomendasi ini menggunakan tautan afiliasi Shopee. Jika Anda membeli melalui tautan tersebut, pengelola dapat menerima komisi tanpa biaya tambahan bagi Anda.',items:[]},premium:{enabled:false,upgradeUrl:'',benefits:[]},privacy:{privacyUrl:'./privacy-policy.html',termsUrl:'./terms.html'}};
let pool;function db(){const connectionString=process.env.DATABASE_URL||process.env.notulensi_POSTGRES_URL||process.env.notulensi_POSTGRES_PRISMA_URL||process.env.notulensi_DATABASE_URL_UNPOOLED;if(!connectionString)throw new Error('DATABASE_URL is not configured.');if(!pool)pool=new Pool({connectionString,max:2,ssl:process.env.DATABASE_SSL==='disable'?false:{rejectUnauthorized:false}});return pool;}
function mergeConfig(value){const o=value&&typeof value==='object'?value:{};return {...DEFAULT_CONFIG,...o,affiliate:{...DEFAULT_CONFIG.affiliate,...(o.affiliate||{}),items:Array.isArray(o.affiliate?.items)?o.affiliate.items:[]},adsense:{...DEFAULT_CONFIG.adsense,...(o.adsense||{})},premium:{...DEFAULT_CONFIG.premium,...(o.premium||{})},privacy:{...DEFAULT_CONFIG.privacy,...(o.privacy||{})}};}
function cleanText(v,max=2000){return typeof v==='string'?v.trim().slice(0,max):''}
function cleanList(v,max=30){return Array.isArray(v)?[...new Set(v.map(x=>cleanText(x,80).toLowerCase()).filter(Boolean))].slice(0,max):[]}
function validate(config){const c=mergeConfig(config);if(c.affiliate.items.length>500)throw new Error('Maximum 500 affiliate items.');const seen=new Set();for(const item of c.affiliate.items){if(!item||typeof item!=='object')throw new Error('Invalid affiliate item.');item.id=cleanText(item.id,120);item.title=cleanText(item.title);item.description=cleanText(item.description);item.url=cleanText(item.url,4000);item.label=cleanText(item.label,200)||'Lihat di Shopee';item.category=cleanText(item.category,80).toLowerCase();item.categories=cleanList(item.categories);item.tags=cleanList(item.tags,40);item.priority=Math.max(0,Math.min(100,Number(item.priority)||0));item.weight=Math.max(1,Math.min(100,Number(item.weight)||50));item.frequencyCap=Math.max(0,Math.min(20,Number(item.frequencyCap)||0));item.enabled=item.enabled!==false;if(!item.id||seen.has(item.id))throw new Error('Affiliate item IDs must be unique.');seen.add(item.id);if(item.url&&!/^https?:\/\//i.test(item.url))throw new Error(`Invalid affiliate URL for ${item.id}.`);}return c;}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.keys(value).sort().reduce((o,k)=>(o[k]=stable(value[k]),o),{});return value;}
function same(a,b){return JSON.stringify(stable(a))===JSON.stringify(stable(b));}
async function ensureTable(client){await client.query(`CREATE TABLE IF NOT EXISTS notulensi_monetization_config (config_key TEXT PRIMARY KEY, config JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='GET'&&req.method!=='PUT')return res.status(405).json({error:'Method not allowed'});let session=null;if(req.method==='PUT'){session=requireAdmin(req,res);if(!session)return;}let client;try{client=await db().connect();await ensureTable(client);const result=await client.query('SELECT config FROM notulensi_monetization_config WHERE config_key=$1',['default']);const current=mergeConfig(result.rows[0]?.config||{});if(req.method==='GET')return res.status(200).json({config:current,updated:Boolean(result.rows[0])});const incoming=req.body?.config||req.body||{};const config=validate(mergeConfig({...current,...incoming,affiliate:{...current.affiliate,...(incoming.affiliate||{})},adsense:{...current.adsense,...(incoming.adsense||{})},premium:{...current.premium,...(incoming.premium||{})},privacy:{...current.privacy,...(incoming.privacy||{})}}));await client.query(`INSERT INTO notulensi_monetization_config(config_key,config,updated_at) VALUES($1,$2::jsonb,NOW()) ON CONFLICT(config_key) DO UPDATE SET config=EXCLUDED.config,updated_at=NOW()`,['default',JSON.stringify(config)]);const verify=await client.query('SELECT config FROM notulensi_monetization_config WHERE config_key=$1',['default']);const persisted=mergeConfig(verify.rows[0]?.config||{});if(!same(persisted,config))throw new Error('Persistence verification failed.');return res.status(200).json({saved:true,verified:true,config:persisted,role:session.role});}catch(error){console.error('monetization-config',error);return res.status(503).json({error:error?.message==='Persistence verification failed.'?error.message:error?.message||'Server-side monetization storage is unavailable.'});}finally{if(client)client.release();}}
